import { useState, useEffect, useMemo } from 'react';
import { Lightbulb, ArrowUpRight, ShieldCheck, Gauge } from 'lucide-react';
import KPICard from '../components/ui/KPICard';
import ChartCard from '../components/ui/ChartCard';
import RiskBadge, { getRiskColor } from '../components/ui/RiskBadge';
import LoadingSpinner from '../components/ui/LoadingSpinner';
import { fetchFSRIData } from '../lib/api';

const IMPACT_COLORS = { High: '#ef4444', Medium: '#f59e0b', Low: '#22c55e' };

export default function RecommendationPage() {
  const [fsriData, setFsriData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState('');

  useEffect(() => {
    fetchFSRIData().then(d => setFsriData(d)).finally(() => setLoading(false));
  }, []);

  const countries = useMemo(() => [...new Set(fsriData.map(r => r.Country))].sort(), [fsriData]);
  useEffect(() => { if (countries.length && !selected) setSelected(countries[0]); }, [countries, selected]);

  const latestYear = useMemo(() => Math.max(...fsriData.map(r => r.Year)), [fsriData]);
  const countryData = useMemo(() => fsriData.find(r => r.Country === selected && r.Year === latestYear), [fsriData, selected, latestYear]);

  const riskCategory = countryData?.FSRI_Category || 'Safe';
  
  // Dynamic IF-THEN rules based on user request
  const getRules = (data) => {
    if (!data) return [];
    const rules = [];
    
    // Condition 1: Production
    if (data.Production < 100000000) {
      rules.push({
        condition: 'Produksi turun',
        action: 'Increase fertilizer subsidy',
        priority: 1, impact: 'High', confidence: 0.92
      });
    } else {
       rules.push({
        condition: 'Rice production rendah',
        action: 'Increase domestic rice production',
        priority: 2, impact: 'Medium', confidence: 0.85
      });
    }

    // Condition 2: Trade Dependency
    if (data.Self_Sufficiency_Ratio < 0.8) {
      rules.push({
        condition: 'Import dependency tinggi',
        action: 'Diversify food import sources',
        priority: 1, impact: 'High', confidence: 0.88
      });
    }

    // Condition 3: Food availability
    if (data.Food_Availability_Index < 40) {
       rules.push({
        condition: 'Food availability index rendah',
        action: 'Increase irrigation investment',
        priority: 2, impact: 'Medium', confidence: 0.75
      });
    }

    return rules.length ? rules : [
      { condition: 'Kondisi stabil', action: 'Maintain current policies', priority: 3, impact: 'Low', confidence: 0.95 }
    ];
  };

  const recommendations = getRules(countryData);
  const riskScore = countryData ? 100 - countryData.FSRI : 0;

  if (loading) return <LoadingSpinner text="Loading recommendations..." />;

  return (
    <div>
      <div className="page-header" style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }}>
        <div>
          <h1>AI Recommendations</h1>
          <p>Actionable insights generated by our Recommendation Engine</p>
        </div>
        <select className="filter-select" value={selected} onChange={e => setSelected(e.target.value)} id="rec-country-selector" style={{ minWidth: 220 }}>
          {countries.map(c => <option key={c} value={c}>{c}</option>)}
        </select>
      </div>

      {countryData && (
        <>
          {/* Country Summary */}
          <div className="grid-row grid-cols-4" style={{ marginBottom: 24 }}>
            <KPICard icon={ShieldCheck} label="Risk Score" value={riskScore} color={riskScore < 40 ? 'emerald' : riskScore < 60 ? 'amber' : 'red'} />
            <KPICard icon={Gauge} label="Risk Level" value={riskCategory} color={riskCategory === 'Very Safe' || riskCategory === 'Safe' ? 'emerald' : riskCategory === 'Medium' ? 'amber' : 'red'} />
            <KPICard icon={Lightbulb} label="Active Rules" value={recommendations.length} color="sky" />
            <KPICard icon={ArrowUpRight} label="Avg Confidence" value={`${(recommendations.reduce((s, r) => s + r.confidence, 0) / recommendations.length * 100).toFixed(0)}%`} color="purple" />
          </div>

          {/* IF-THEN Recommendation Cards */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            {recommendations.map((rec, i) => (
              <div key={i} className="card animate-in" style={{ padding: 24, display: 'flex', alignItems: 'center', gap: 24 }}>
                
                {/* Condition Box */}
                <div style={{ flex: 1, padding: 16, background: 'var(--bg-input)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-medium)' }}>
                  <span style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--accent-amber)', letterSpacing: '0.05em' }}>JIKA</span>
                  <h3 style={{ fontSize: '1.1rem', marginTop: 4 }}>{rec.condition}</h3>
                </div>

                <div style={{ flexShrink: 0, color: 'var(--text-muted)' }}>
                  <ArrowUpRight size={24} />
                </div>

                {/* Action Box */}
                <div style={{ flex: 1, padding: 16, background: 'rgba(16, 185, 129, 0.05)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-accent)' }}>
                  <span style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--accent-emerald)', letterSpacing: '0.05em' }}>MAKA</span>
                  <h3 style={{ fontSize: '1.1rem', marginTop: 4, color: 'var(--accent-emerald)' }}>{rec.action}</h3>
                </div>

                {/* Metadata */}
                <div style={{ width: 140, display: 'flex', flexDirection: 'column', gap: 8, fontSize: '0.82rem' }}>
                   <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                      <span style={{ color: 'var(--text-muted)' }}>Priority</span>
                      <span style={{ fontWeight: 600, color: rec.priority === 1 ? 'var(--accent-red)' : rec.priority === 2 ? 'var(--accent-amber)' : 'var(--accent-emerald)' }}>P{rec.priority}</span>
                   </div>
                   <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                      <span style={{ color: 'var(--text-muted)' }}>Confidence</span>
                      <span style={{ fontWeight: 600, color: 'var(--accent-sky)' }}>{(rec.confidence * 100).toFixed(0)}%</span>
                   </div>
                </div>

              </div>
            ))}
          </div>

          <div style={{ marginTop: 24, fontSize: '0.85rem', color: 'var(--text-muted)', textAlign: 'center' }}>
            Ini mengubah hasil prediksi menjadi keputusan yang dapat ditindaklanjuti (actionable insight).
          </div>
        </>
      )}
    </div>
  );
}
